apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-pollers-conf
  labels:
    app: librenms-pollers
data:
  config-interfaces-php: |
    <?php

    $config['bad_if_regexp'][] = '/^docker[-\w].*$/';
    $config['bad_if_regexp'][] = '/^lxcbr[0-9]+$/';
    $config['bad_if_regexp'][] = '/^veth.*$/';
    $config['bad_if_regexp'][] = '/^virbr.*$/';
    $config['bad_if_regexp'][] = '/^lo$/';
    $config['bad_if_regexp'][] = '/^macvtap.*$/';
    $config['bad_if_regexp'][] = '/gre.*$/';
    $config['bad_if_regexp'][] = '/tun[0-9]+$/';
  config-rrdcached-php: |
    <?php

    $config['rrdcached'] = 'rrdcached:42217';
  config-distributed-poller-php: |
    <?php

    $config['distributed_poller']                = true;
    $config['distributed_poller_group']          = 0;
    $config['distributed_poller_memcached_host'] = 'memcached';
    $config['distributed_poller_memcached_port'] = '11211';
  config-poller-php: |
    <?php

    $config['distributed_poller_name']           = file_get_contents('/etc/hostname');
    $config['distributed_poller']                = true;
    $config['distributed_poller_group']          = 0;
    $config['distributed_poller_memcached_host'] = 'memcached';
    $config['distributed_poller_memcached_port'] = '11211';
    $config['update']                            = 0;
---
# for versions before 1.8.0 use apps/v1beta1
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: librenms-pollers
spec:
  selector:
    matchLabels:
      app: librenms-pollers
  serviceName: librenms-pollers
  replicas: 1
  template:
    metadata:
      labels:
        app: librenms-pollers
    spec:
      containers:
      - name: librenms-pollers
        image: jarischaefer/docker-librenms
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          value: "librenms"
        - name: DB_USER
          value: "newuser"
        - name: DB_PASS
          value: "password"
        - name: BASE_URL
          value: "http://localhost/"
        - name: TZ
          value: "UTC"
        - name: DAILY_ENABLE
          value: "false"
        - name: ALERTS_ENABLE
          value: "false"
        - name: POLL_BILLING_ENABLE
          value: "false"
        - name: BILLING_CALCULATE_ENABLE
          value: "false"
        - name: CHECK_SERVICES_ENABLE
          value: "false"
        # ports:
        # - name: librenms-http
          # containerPort: 80
        # - name: librenms-https
          # containerPort: 443
        volumeMounts:
        - mountPath: /opt/librenms/conf.d
          name: librenms-pollers-conf
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        # readinessProbe:
          # tcpSocket:
            # port: 80
          # initialDelaySeconds: 5
          # periodSeconds: 10
        # livenessProbe:
          # tcpSocket:
            # port: 80
          # initialDelaySeconds: 15
          # periodSeconds: 20
      volumes:
        - name: librenms-pollers-conf
          configMap:
            name: librenms-pollers-conf
            items:
            - key: config-interfaces-php
              path: interfaces.php
            - key: config-rrdcached-php
              path: rrdcached.php
            - key: config-poller-php
              path: poller.php
