---
apiVersion: v1
kind: Service
metadata:
  name: librenms
  labels:
    app: librenms
spec:
  type: NodePort
  ports:
  - port: 80
    name: librenms-http
    nodePort: 31971
  - port: 443
    name: librenms-https
  selector:
    app: librenms
---
# for versions before 1.8.0 use apps/v1beta1
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: librenms
spec:
  selector:
    matchLabels:
      app: librenms
  serviceName: librenms
  replicas: 1
  template:
    metadata:
      labels:
        app: librenms
    spec:
      initContainers:
      - name: init-librenmsdb
        image: jarischaefer/docker-librenms
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          value: "librenms"
        - name: DB_USER
          value: "newuser"
        - name: DB_PASS
          value: "password"
        - name: BASE_URL
          value: "http://192.168.99.100:31971/"
        - name: TZ
          value: "UTC"
        command:
        - su
        - "--preserve-environment"
        - "librenms"
        - "-c"
        - "cd /opt/librenms && php /opt/librenms/build-base.php && php /opt/librenms/adduser.php admin admin 10 test@example.com"
      containers:
      - name: librenms
        image: jarischaefer/docker-librenms
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          value: "librenms"
        - name: DB_USER
          value: "newuser"
        - name: DB_PASS
          value: "password"
        - name: BASE_URL
          value: "http://192.168.99.100:31971/"
        - name: TZ
          value: "UTC"
        - name: DISABLE_DISCOVERY
          value: "true"
        - name: DISABLE_POLLERS
          value: "true"
        ports:
        - name: librenms-http
          containerPort: 80
        - name: librenms-https
          containerPort: 443
        volumeMounts:
        - name: librelogs
          mountPath: /opt/librenms/logs
        # - name: libressl
          # mountPath: /etc/nginx/ssl
        - mountPath: /opt/librenms/conf.d
          name: librenms-conf
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
        - name: librenms-conf
          configMap:
            name: librenms-conf
            items:
            - key: config-interfaces-php
              path: interfaces.php
            - key: config-rrdcached-php
              path: rrdcached.php
            - key: config-distributed-poller-php
              path: distributed_poller.php
  volumeClaimTemplates:
  - metadata:
      name: librelogs
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
  # - metadata:
      # name: libressl
    # spec:
      # accessModes: ["ReadWriteOnce"]
      # resources:
        # requests:
          # storage: 1Gi
