apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  ports:
  - port: 11211
  selector:
    app: memcached
  clusterIP: None
---
# for versions before 1.8.0 use apps/v1beta1
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: memcached
spec:
  selector:
    matchLabels:
      app: memcached
  serviceName: memcached
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached
        args: ["-m 64 -p 11211 -p 0.0.0.0"]
        ports:
        - containerPort: 11211
          protocol: TCP
        # resources:
          # requests:
            # cpu: 500m
            # memory: 1Gi
        # readinessProbe:
          # tcpSocket:
            # port: 80
          # initialDelaySeconds: 5
          # periodSeconds: 10
        # livenessProbe:
          # tcpSocket:
            # port: 80
          # initialDelaySeconds: 15
          # periodSeconds: 20
