---
apiVersion: v1
kind: Service
metadata:
  name: rrdcached
spec:
  ports:
  - port: 42217
  selector:
    app: rrdcached
  clusterIP: None
---
# for versions before 1.8.0 use apps/v1beta1
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: rrdcached
spec:
  selector:
    matchLabels:
      app: rrdcached
  serviceName: rrdcached
  replicas: 1
  template:
    metadata:
      labels:
        app: rrdcached
    spec:
      containers:
      - name: rrdcached
        image: furhouse/docker-rrdcached:latest
        env:
        - name: WRITE_TIMEOUT
          value: "900"
        - name: DELAY
          value: "900"
        - name: CACHE_TIMEOUT
          value: "1800"
        ports:
        - containerPort: 42217
          protocol: TCP
        volumeMounts:
        - name: rrdcached
          mountPath: /opt/rrdcached/rrd
        # resources:
          # requests:
            # cpu: 500m
            # memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 42217
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 42217
          initialDelaySeconds: 15
          periodSeconds: 20
  volumeClaimTemplates:
  - metadata:
      name: rrdcached
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
